version: "3.8"

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis-service
    ports:
      - "6379:6379"
    restart: always

  python-service:
    build:
      context: ./app
    container_name: python-service
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command: python main.py
